version: '3'

services:
    web:
        image: golang:alpine
        build: .
        container_name: app
        volumes:
            - .:/home/application/current
        working_dir: /home/application/current
        ports:
            - "8081:8080"
        depends_on:
            - db
        links:
            - db
        command: tail -f /dev/null
        networks:
            - app-network
    db:
        image: postgres:latest
        container_name: app_db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456
            - POSTGRES_ROOT_PASSWORD=123456
        ports:
            - "5433:5432"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
